baseURL = "https://meditation.neverfapdeluxe.com/"
title = "NeverFap Deluxe Meditation | Get Immediate Help With Your Porn Addiction."
languageCode = "en-us"
theme = "meditation_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-4"
